port: 4000
permalink: /:year/:month/:day/:title
rdiscount extensions: [smart]
pygments: true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "tables"]
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'Rakefile']
